name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  gradle-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon --stacktrace

      - name: Deploy to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: blueoasis/github-actions-demo
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
