name: Debug GitHub Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allows manual triggering from the GitHub UI

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print debug info
        run: |
          echo "GitHub Actions is working!"
          echo "Current date: $(date)"
          echo "Running on: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"

